models:
  - name: mobilenet-ssd-cf
    launchers:
      - framework: caffe
        model:   public/mobilenet-ssd/mobilenet-ssd.prototxt
        weights: public/mobilenet-ssd/mobilenet-ssd.caffemodel
        adapter: ssd
    datasets:
      - name: VOC2007
        preprocessing:
          - type: resize
            size: 300
          - type: normalization
            mean: 127.5
            std:  127.5
        postprocessing:
          - type: resize_prediction_boxes

  - name: mobilenet-ssd
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: models/mobilenet-ssd/FP32/mobilenet-ssd.xml
        weights: models/mobilenet-ssd/FP32/mobilenet-ssd.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   models/mobilenet-ssd/FP16/mobilenet-ssd.xml
        weights: models/mobilenet-ssd/FP16/mobilenet-ssd.bin
        adapter: classification

    datasets:
      - name: VOC2012
        preprocessing:
          - type: resize
            size: 300
          - type: normalization
            mean: 127.5
            std:  127.5
        postprocessing:
          - type: resize_prediction_boxes
        annotation_conversion:
          converter: voc_detection
          annotations_dir: dataset/VOCdevkit/VOC2012/Annotations
          images_dir: dataset/VOCdevkit/VOC2012/JPEGImages
          imageset_file: dataset/VOCdevkit/VOC2012/ImageSets/Main/val.txt
        data_source: dataset/VOCdevkit/VOC2012/JPEGImages
        annotation: dataset_files/voc12.pickle
        dataset_meta: dataset_files/voc12.json
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: True
            presenter: print_scalar

global_definitions: dataset_definitions.yml
